export const POPULAR_ITEMS = [
  {
    title: "До 16,1% годовых по вкладу «Новые деньги»",
    desc: "Ставка выше для новых накоплений",
    bgColor: "bg-blue-500",
    textColor: "text-white",
    bgArrowColor: "bg-white",
    ArrowColor: "text-black",
    src: "/Popular/deposit.png",
    imgPos: "lg:translate-x-0 xl:translate-x-0 lg:w-full",
  },
  {
    title: "Кредит наличными",
    desc: "",
    bgColor: "bg-blue-500",
    textColor: "text-white",
    bgArrowColor: "bg-white",
    ArrowColor: "text-black",
    src: "/Popular/credit_nalich.png",
    imgPos: "max-w-[736px] lg:translate-x-100 xl:translate-x-40",
  },
  {
    title: "Кредитная карта с гибкими условиями",
    desc: "Управляйте льготным периодом",
    bgColor: "bg-[#f5f5f5]",
    textColor: "text-black",
    bgArrowColor: "bg-black",
    ArrowColor: "text-white",
    src: "/Popular/credit_card.png",
    imgPos: "max-w-[736px] lg:translate-x-100 xl:translate-x-40",
  },
  {
    title: "На 10% больше кэшбэка на одежду и обувь ",
    desc: "по премиальной карте",
    bgColor: "",
    textColor: "text-white",
    bgArrowColor: "bg-black",
    ArrowColor: "text-white",
    src: "/Popular/odejda_i_obyv.png",
    imgPos: "lg:translate-x-0 xl:translate-x-0 lg:w-full",
  },
  {
    title: "Сертификаты Яндекс Афиши за открытие ИИС-3",
    desc: "",
    bgColor: "bg-[#a8dcff]",
    textColor: "text-black",
    bgArrowColor: "bg-black",
    ArrowColor: "text-white",
    src: "/Popular/yandex_cert.png",
    imgPos: "max-w-[736px] max-xl:translate-x-100 xl:right-auto xl:left-40",
  },
  {
    title: "Приводите друзей в Газпромбанк",
    desc: "",
    bgColor: "bg-[#f5f5f5]",
    textColor: "text-black",
    bgArrowColor: "bg-black",
    ArrowColor: "text-white",
    src: "/Popular/frends.png",
    imgPos: "max-w-[736px] max-xl:translate-x-100 xl:right-auto xl:left-40",
  },
];
